version: '3.8'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    command: --strict.perms=false
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../log:/home/logs/:ro
    user: 0:0
    restart: always

networks:
  default:
    external:
      name: loggin