filebeat.inputs:
- type: log
  enabled: true
  paths:
    - "/home/logs/*.json"

  multiline.pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}[[:space:]]\[
  multiline.negate: true
  multiline.match: after

output.logstash:
  hosts: [ "logstash:5044" ]